services:
  server:
    image: server
    build: server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - PORT=${SERVER_PORT}

  frontend:
    image: frontend
    build: frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - PORT=${FRONTEND_PORT}
      - SERVER_URL="http://server:${SERVER_PORT}"

  bot1:
    image: bot1
    build: "${BOT_1_PATH}"
    environment:
      - SERVER_URL="https://server:${SERVER_PORT}"
    depends_on:
      - server

  bot2:
    image: bot2
    build: "${BOT_2_PATH}"
    environment:
      - SERVER_URL="https://server:${SERVER_PORT}"
    depends_on:
      - server